// Generated by CoffeeScript 2.0.0-beta3
(function() {
  module.exports = {
    "README.md": {
      "destination": {
        "base": "README.html",
        "css": "docco.css",
        "dir": "docs",
        "ext": ".html",
        "file": "docs/README.html",
        "name": "README",
        "path": "/Project/docs/README.html",
        "pathdir": "/Project/docs",
        "relativefile": "README.html",
        "root": "/Project"
      },
      "language": {
        "commentFilter": /(^#![\/]|^\s*#\{)/,
        "commentMatcher": /^\s*\s?/,
        "html": true,
        "link": "!",
        "linkMatcher": /^!\[(.+)\]\((.+)\)/,
        "name": "markdown",
        "section": "#",
        "sectionMatcher": /^#\s?/,
        "symbol": ""
      },
      "others": {
        "README.html": {
          "file": "README.md",
          "link": "README.html"
        },
        "fake_coffee.html": {
          "file": "src/fake_coffee.coffee",
          "link": "src/fake_coffee.html"
        },
        "fake_litcoffee.html": {
          "file": "src/lib/fake_litcoffee.litcoffee",
          "link": "src/lib/fake_litcoffee.html"
        },
        "fluffybunny1.jpg": {
          "file": "images/fluffybunny1.jpg",
          "link": "images/fluffybunny1.jpg"
        }
      },
      "source": {
        "base": "README.md",
        "dir": "",
        "ext": ".md",
        "file": "README.md",
        "name": "README",
        "path": "/Project/README.md",
        "relativefile": "README.md",
        "root": "/Project"
      }
    },
    "images/fluffybunny1.jpg": {
      "destination": {
        "base": "fluffybunny1.jpg",
        "css": "../docco.css",
        "dir": "docs/images",
        "ext": ".jpg",
        "file": "docs/images/fluffybunny1.jpg",
        "name": "fluffybunny1",
        "path": "/Project/docs/images/fluffybunny1.jpg",
        "pathdir": "/Project/docs/images",
        "relativefile": "images/fluffybunny1.jpg",
        "root": "/Project"
      },
      "language": {
        "commentFilter": /(^#![\/]|^\s*#\{)/,
        "commentMatcher": /^\s*undefined\s?/,
        "copy": true,
        "name": "image"
      },
      "others": {
        "README.html": {
          "file": "README.md",
          "link": "../README.html"
        },
        "fake_coffee.html": {
          "file": "src/fake_coffee.coffee",
          "link": "../src/fake_coffee.html"
        },
        "fake_litcoffee.html": {
          "file": "src/lib/fake_litcoffee.litcoffee",
          "link": "../src/lib/fake_litcoffee.html"
        },
        "fluffybunny1.jpg": {
          "file": "images/fluffybunny1.jpg",
          "link": "fluffybunny1.jpg"
        }
      },
      "source": {
        "base": "fluffybunny1.jpg",
        "dir": "images",
        "ext": ".jpg",
        "file": "images/fluffybunny1.jpg",
        "name": "fluffybunny1",
        "path": "/Project/images/fluffybunny1.jpg",
        "relativefile": "images/fluffybunny1.jpg",
        "root": "/Project"
      }
    },
    "src/fake_coffee.coffee": {
      "destination": {
        "base": "fake_coffee.html",
        "css": "../docco.css",
        "dir": "docs/src",
        "ext": ".html",
        "file": "docs/src/fake_coffee.html",
        "name": "fake_coffee",
        "path": "/Project/docs/src/fake_coffee.html",
        "pathdir": "/Project/docs/src",
        "relativefile": "src/fake_coffee.html",
        "root": "/Project"
      },
      "language": {
        "commentFilter": /(^#![\/]|^\s*#\{)/,
        "commentMatcher": /^\s*#\s?/,
        "multiline": {
          "start": "###",
          "stop": "###"
        },
        "name": "coffeescript",
        "startMatcher": /^\s*\#\#\#/,
        "stopMatcher": /^\s*\#\#\#/,
        "symbol": "#"
      },
      "others": {
        "README.html": {
          "file": "README.md",
          "link": "../README.html"
        },
        "fake_coffee.html": {
          "file": "src/fake_coffee.coffee",
          "link": "fake_coffee.html"
        },
        "fake_litcoffee.html": {
          "file": "src/lib/fake_litcoffee.litcoffee",
          "link": "lib/fake_litcoffee.html"
        },
        "fluffybunny1.jpg": {
          "file": "images/fluffybunny1.jpg",
          "link": "../images/fluffybunny1.jpg"
        }
      },
      "source": {
        "base": "fake_coffee.coffee",
        "dir": "src",
        "ext": ".coffee",
        "file": "src/fake_coffee.coffee",
        "name": "fake_coffee",
        "path": "/Project/src/fake_coffee.coffee",
        "relativefile": "src/fake_coffee.coffee",
        "root": "/Project"
      }
    },
    "src/lib/fake_litcoffee.litcoffee": {
      "destination": {
        "base": "fake_litcoffee.html",
        "css": "../../docco.css",
        "dir": "docs/src/lib",
        "ext": ".html",
        "file": "docs/src/lib/fake_litcoffee.html",
        "name": "fake_litcoffee",
        "path": "/Project/docs/src/lib/fake_litcoffee.html",
        "pathdir": "/Project/docs/src/lib",
        "relativefile": "src/lib/fake_litcoffee.html",
        "root": "/Project"
      },
      "language": {
        "commentFilter": /(^#![\/]|^\s*#\{)/,
        "commentMatcher": /^\s*#\s?/,
        "literate": true,
        "name": "coffeescript",
        "symbol": "#"
      },
      "others": {
        "README.html": {
          "file": "README.md",
          "link": "../../README.html"
        },
        "fake_coffee.html": {
          "file": "src/fake_coffee.coffee",
          "link": "../fake_coffee.html"
        },
        "fake_litcoffee.html": {
          "file": "src/lib/fake_litcoffee.litcoffee",
          "link": "fake_litcoffee.html"
        },
        "fluffybunny1.jpg": {
          "file": "images/fluffybunny1.jpg",
          "link": "../../images/fluffybunny1.jpg"
        }
      },
      "source": {
        "base": "fake_litcoffee.litcoffee",
        "dir": "src/lib",
        "ext": ".litcoffee",
        "file": "src/lib/fake_litcoffee.litcoffee",
        "name": "fake_litcoffee",
        "path": "/Project/src/lib/fake_litcoffee.litcoffee",
        "relativefile": "src/lib/fake_litcoffee.litcoffee",
        "root": "/Project"
      }
    }
  };

}).call(this);

//# sourceMappingURL=informationOnFilesUnFlattened.js.map
