// Generated by CoffeeScript 1.3.3

/* 
A simple script to enable command line invocation docco.coffee,
which is a library, and not directly runnable.
*/


(function() {

  (require('./docco')).run();

}).call(this);
