// Generated by CoffeeScript 2.0.0-beta3
(function() {
  var buildMatchers;

  module.exports = buildMatchers = function(languages) {
    var ext, l, start, stop;
    for (ext in languages) {
      l = languages[ext];
      l.commentMatcher = RegExp(`^\\s*${l.symbol}\\s?`);
      l.commentFilter = /(^#![\/]|^\s*#\{)/;
      if (l.link) {
        l.linkMatcher = RegExp(`^${l.link}\\[(.+)\\]\\((.+)\\)`);
      }
      if (l.section) {
        l.sectionMatcher = RegExp(`^${l.section}\\s?`);
      }
      if (l.multiline) {
        start = l.multiline.start.replace(/(.{1})/g, "\\$1");
        stop = l.multiline.stop.replace(/(.{1})/g, "\\$1");
        l.startMatcher = RegExp(`^\\s*${start}`);
        l.stopMatcher = RegExp(`^\\s*${stop}`);
      }
    }
    return languages;
  };

}).call(this);

//# sourceMappingURL=buildMatchers.js.map
